services:
  postgres:
    image: postgis/postgis:14-3.4-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "altlocdb"
    networks:
      - dev

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "altlocdev"
      MINIO_ROOT_PASSWORD: "miniopswd"
    volumes:
      - minio-data:/data
    networks:
      - dev

  altloc-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: altloc-backend
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/altlocdb"
      SPRING_DATASOURCE_USERNAME: "dev"
      SPRING_DATASOURCE_PASSWORD: "dev"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "UVb8udA0kRnJ0DGuoguP"
      MINIO_SECRET_KEY: "oQCrn2ewLlULAVgJhGjEHyV4kmOXoDnx3xo8zf3D"
      MINIO_BUCKET: "altloc"
      MINIO_ROOT_USER: "altlocdev"
      MINIO_ROOT_PASSWORD: "miniopswd"
      MINIO_REGION: "us-east-1"
    depends_on:
      - postgres
      - minio
    ports:
      - "4000:4000"
    networks:
      - dev

networks:
  dev:
    external: true

volumes:
  postgres-data:
  minio-data:
